#!/bin/bash
set -euo pipefail

TERRAFORM_DIR="../terraform"
INVENTORY_FILE="../ansible/inventory.ini"
SSH_KEY="../terraform/generated/ssh_key.pem"

echo "Reading Terraform outputs..."

WEB_IP=$(terraform -chdir="${TERRAFORM_DIR}" output -raw web_public_ip)
DB_IP=$(terraform -chdir="${TERRAFORM_DIR}" output -raw db_private_ip)
ADMIN_USER=$(terraform -chdir="${TERRAFORM_DIR}" output -raw admin_username)

if [[ -z "${WEB_IP}" || -z "${DB_IP}" ]]; then
  echo "ERROR: Could not read Terraform outputs. Did you run terraform apply?"
  exit 1
fi

cat > "${INVENTORY_FILE}" << EOI
# Auto-generated by scripts/generate-inventory.sh - DO NOT EDIT MANUALLY

[web]
web-server ansible_host=${WEB_IP}

[db]
db-server ansible_host=${DB_IP} ansible_ssh_common_args='-o ProxyCommand="ssh -i ${SSH_KEY} -W %h:%p -q ${ADMIN_USER}@${WEB_IP}"'

[all:vars]
ansible_user=${ADMIN_USER}
ansible_private_key_file=${SSH_KEY}
ansible_python_interpreter=/usr/bin/python3
EOI

echo "Inventory generated at ${INVENTORY_FILE}"
echo "  web-server (public) -> ${WEB_IP}"
echo "  db-server (private, via jump) -> ${DB_IP}"
