#!/bin/bash
set -euo pipefail

# Run this after every `terraform apply` and before running Ansible.

TERRAFORM_DIR="../terraform"
INVENTORY_FILE="../ansible/inventory.ini"

echo "Reading Terraform outputs..."

WEB_IP=$(terraform -chdir="${TERRAFORM_DIR}" output -raw web_public_ip)
DB_IP=$(terraform -chdir="${TERRAFORM_DIR}" output -raw db_public_ip)
ADMIN_USER=$(terraform -chdir="${TERRAFORM_DIR}" output -raw admin_username)

if [[ -z "${WEB_IP}" || -z "${DB_IP}" ]]; then
  echo "ERROR: Could not read Terraform outputs. Did you run 'terraform apply'?"
  exit 1
fi

cat > "${INVENTORY_FILE}" << EOF

# Auto-generated by scripts/generate-inventory.sh - DO NOT EDIT MANUALLY
# Regenerate with: ./scripts/generate-inventory.sh

[web]
web-server ansible_host=${WEB_IP}

[db]
db-server ansible_host=${DB_IP}

[all:vars]
ansible_user=${ADMIN_USER}
ansible_python_interpreter=/usr/bin/python3
EOF

echo "Inventory generated at ${INVENTORY_FILE}"
echo "  web-server -> ${WEB_IP}"
echo "  db-server  -> ${DB_IP}"
