---
- name: Harden and configure all servers
  hosts: all
  become: true
  roles:
    - security
    - node_exporter

- name: Configure web server
  hosts: web
  become: true
  roles:
    - docker
    - nginx
    - app
    - monitoring

- name: Configure database server
  hosts: db
  become: true
  roles:
    - docker
    - postgres
